### PR TITLE
Update registry with SymbolicRegression.jl

### PR DESCRIPTION
**Pull request by MilesCranmer**
Closes https://github.com/alan-turing-institute/MLJ.jl/issues/1032

(I wasn't sure if we were supposed to do it ourselves or not; feel free to close if needed. I just followed the instructions in `MLJModels.@update`.)

Since the SymbolicRegression.jl docstrings are technically invalid right now as they describe the `@load` API: https://astroautomata.com/SymbolicRegression.jl/dev/api/, let me know the timescale for the registry update and if I should update the docstrings with a temporary fix.

Thanks!
Miles

### CODE REVIEW

**Comment by OkonSamuel** [comment]
> @OkonSamuel @ablaom sorry to bother you, but I was wondering when this could be put up on the registry? I am just a bit worried about new users, because the SymbolicRegression.jl docstrings currently have the `@load` syntax, but this will not work until the registry is updated.
> 
> Thanks! Miles

I planned to close this today.

**Comment by OkonSamuel** [comment]
closing in favor of #521

**Comment by MilesCranmer** [comment]
Thanks!

**Comment by OkonSamuel** [comment]
Yes. I'll go ahead and tag a new release.

**Pull request closed without merging**
