### PR TITLE
Add two `SIRUS.jl` models

### PR DESCRIPTION
**Pull request by rikhuijzer**
It took a bit longer than expected, but finally regression was implemented for `SIRUS.jl`. I've tried to explain at the [Julia Discourse](https://discourse.julialang.org/t/ann-sirus-jl-v1-2-interpretable-machine-learning-via-rule-extraction/100932) why this is a useful model. Hopefully the `StableRulesClassifier` and `StableRulesRegressor` can be added to `MLJModels.jl` :smile:

### CODE REVIEW

**Comment by ablaom** [comment]
Congratulations! Looks like a very thorough piece of work. 

I'm currently on leave so copying @OkonSamuel in here. I strongly suggest you take a look at:

- [ ]  https://github.com/rikhuijzer/SIRUS.jl/issues/29

**Comment by OkonSamuel** [comment]
Thanks @rikhuijzer I'll review this weekend.

**Comment by ablaom** [comment]
See also https://github.com/rikhuijzer/SIRUS.jl/issues/32.

**Comment by OkonSamuel** [comment]
Thanks @rikhuijzer. This is indeed a great addition.
Your code is clean :smile:
Just adjust the docstrings a bit to match the mlj standard.

**Comment by rikhuijzer** [comment]
I hope this is now conforming the spec. I also refactored the code a bit in https://github.com/rikhuijzer/SIRUS.jl/pull/37 and things are definitely more clear now :+1: 

If this PR is accepted, then I'll register the new SIRUS.jl version with the updated docstrings (v1.2.2).

**Comment by OkonSamuel** [comment]
> I hope this is now conforming the spec. I also refactored the code a bit in [rikhuijzer/SIRUS.jl#37](https://github.com/rikhuijzer/SIRUS.jl/pull/37) and things are definitely more clear now 👍
> 
> If this PR is accepted, then I'll register the new SIRUS.jl version with the updated docstrings (v1.2.2).

@rikhuijzer Thanks for addressing most of the issues raised. I'm sorry for being so meticulous here but there are just a few more things that needed to be added/removed before merging.
- [x] Avoid using `docstring` keyword in the `metadata_model` helper. I have opened a PR [here](https://github.com/rikhuijzer/SIRUS.jl/pull/38) to handle that.
- [ ]  Add `Operations` and `Fitted parameters` section to the docstring. You can use  https://github.com/JuliaAI/NearestNeighborModels.jl/blob/dev/src/models.jl#L575-L583 as template for Classification and https://github.com/JuliaAI/NearestNeighborModels.jl/blob/dev/src/models.jl#L731-L736 as a template for Regression. Feel free to adjust the descriptions to match your model's context. Since you didn't define a `fitted_params` specific to your model types, mlj calls the [default implementation](https://github.com/JuliaAI/MLJModelInterface.jl/blob/dev/src/model_api.jl#L102).
- [ ] Although Optional, it is highly recommended you add an `Examples` section. You can use the one you defined [here](https://github.com/rikhuijzer/SIRUS.jl/tree/main#example)

I'm happy to help out in a way I can.

**Comment by rikhuijzer** [comment]
Thank you for the review and pull request, @OkonSamuel. Apologies for the slow response. It took me a while to get to it due to PhD-project demands. I have omitted the `Examples` section because of the trade-off in computation time and ease of testing. If I add an example section, then I would like to add doctests, but at the same time the documenter and tests already take very long. Also, the examples should be clear for readers since it is the core feature of MLJ and since I've added it to the README.

Apart from that, I've merged your PR (thanks again for that) and added `Operations` and `Fitted parameter` sections as well as document and exported the returned object (that is, `StableForest` or `StableRules`).

**Comment by OkonSamuel** [comment]
> Member

Thanks @rikhuijzer for finding the time to add these sections.
I just noticed the the Regressor models subtype `Probabilistic` rather than `Deterministic`. I have opened an issue [here](https://github.com/rikhuijzer/SIRUS.jl/issues/40)

**Comment by rikhuijzer** [comment]
> I just noticed the the Regressor models subtype `Probabilistic` rather than `Deterministic`. I have opened an issue [here](https://github.com/rikhuijzer/SIRUS.jl/issues/40)

I love it! Another bug fixed 😄

**Comment by rikhuijzer** [comment]
Friendly bump, @OkonSamuel

**Comment by OkonSamuel** [comment]
> Friendly bump, @OkonSamuel

Hello @rikhuijzer. 
This PR is ready to be merged. 
Could you tag a new release of your package? Since you made some changes that would affect mlj.
After you do that, I'll open a new PR to add your model.

**Comment by rikhuijzer** [comment]
Friendly bump @OkonSamuel

**Comment by OkonSamuel** [comment]
closing in favor of #524

**Pull request closed without merging**
